// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';
import {tunnel} from '../models';

export function AddConnection(arg1:dto.ConnectionInput):Promise<model.Host>;

export function AddForward(arg1:model.Forward):Promise<model.Forward>;

export function CreateHost(arg1:model.Host):Promise<model.Host>;

export function DeleteForward(arg1:number):Promise<void>;

export function DeleteHost(arg1:number):Promise<void>;

export function GetHost(arg1:number):Promise<model.Host>;

export function GetStatus():Promise<tunnel.Status>;

export function ListHosts():Promise<Array<model.Host>>;

export function ListSSHKeys():Promise<Array<dto.SSHKey>>;

export function PickSSHKey():Promise<string>;

export function ReconnectHost(arg1:number):Promise<void>;

export function SetHostKey(arg1:number,arg2:string):Promise<model.Host>;

export function UpdateForward(arg1:model.Forward):Promise<model.Forward>;

export function UpdateHost(arg1:model.Host):Promise<model.Host>;
