// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function AddForward(arg1) {
  return window['go']['main']['App']['AddForward'](arg1);
}

export function CreateHost(arg1) {
  return window['go']['main']['App']['CreateHost'](arg1);
}

export function DeleteForward(arg1) {
  return window['go']['main']['App']['DeleteForward'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function GetHost(arg1) {
  return window['go']['main']['App']['GetHost'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function UpdateForward(arg1) {
  return window['go']['main']['App']['UpdateForward'](arg1);
}

export function UpdateHost(arg1) {
  return window['go']['main']['App']['UpdateHost'](arg1);
}
